// bitmap file 
// (c) Technion IIT, Department of Electrical and Computer Engineering 2023 
// generated by the automatic Python tool 
 
 
 module flyingBirdBitMap (

					input	logic	clk, 
					input	logic	resetN, 
					input logic	[10:0] offsetX,// offset from top left  position 
					input logic	[10:0] offsetY, 
					input	logic	InsideRectangle, //input that the pixel is within a bracket 
					input logic birdCollision,
					input logic left,

					output	logic	drawingRequest, //output that the pixel should be dispalyed 
					output	logic	[7:0] RGBout,  //rgb value from the bitmap 
					output	logic	[3:0] HitEdgeCode //one bit per edge 
 ) ; 
 
 
// generating the bitmap 
 

localparam logic [7:0] TRANSPARENT_ENCODING = 8'he0 ;// RGB value in the bitmap representing a transparent pixel  
logic[0:31][0:31][7:0] object_colors = {
	{8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0},
	{8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0},
	{8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'hef,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0},
	{8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'h21,8'hef,8'h61,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0},
	{8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'h21,8'hef,8'hef,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0},
	{8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'h80,8'hef,8'hef,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0},
	{8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'h81,8'hef,8'hef,8'he0,8'h80,8'h20,8'h21,8'h20,8'h21,8'h20,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0},
	{8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'h00,8'h61,8'h61,8'hf3,8'hef,8'h20,8'h61,8'h61,8'h61,8'h61,8'h21,8'h20,8'h21,8'h21,8'h20,8'ha0,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0},
	{8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'h00,8'h61,8'h61,8'h61,8'h61,8'hf3,8'hef,8'h61,8'h61,8'h21,8'h61,8'h61,8'h61,8'h21,8'h00,8'h00,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0},
	{8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'h61,8'h61,8'h61,8'h61,8'hf3,8'hef,8'h21,8'h21,8'h61,8'h61,8'h61,8'h61,8'h61,8'h21,8'h21,8'h21,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0},
	{8'he0,8'he0,8'he0,8'he0,8'he0,8'h00,8'h00,8'h21,8'h61,8'h61,8'hf3,8'ha6,8'h21,8'hf3,8'h61,8'h61,8'h61,8'h61,8'h61,8'h61,8'h21,8'h21,8'h21,8'h21,8'h00,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0},
	{8'he0,8'he0,8'he0,8'he0,8'he0,8'h61,8'h81,8'h61,8'h61,8'h00,8'h21,8'h21,8'h61,8'hc7,8'h61,8'h00,8'h00,8'h00,8'h20,8'h61,8'h61,8'h20,8'h20,8'h21,8'h21,8'h21,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0},
	{8'he0,8'he0,8'he0,8'he0,8'h61,8'he0,8'h61,8'h61,8'hc7,8'hc7,8'h65,8'hce,8'hae,8'h61,8'hc6,8'hc7,8'h61,8'h61,8'h61,8'h61,8'h61,8'h21,8'h21,8'h00,8'h21,8'h21,8'h20,8'he0,8'he0,8'he0,8'he0,8'he0},
	{8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'h61,8'hc6,8'hc7,8'hc7,8'hc6,8'h86,8'hce,8'hc7,8'hc7,8'hc7,8'hc7,8'ha2,8'h61,8'h61,8'h61,8'h21,8'h21,8'h21,8'h00,8'he0,8'h60,8'he0,8'he0,8'he0,8'he0,8'he0},
	{8'he0,8'he0,8'he0,8'he0,8'he0,8'h61,8'h20,8'hc6,8'h00,8'h20,8'h61,8'h20,8'h60,8'h60,8'hc6,8'ha2,8'hc7,8'hc7,8'h61,8'h61,8'h61,8'h21,8'h21,8'h21,8'h21,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0},
	{8'he0,8'he0,8'he0,8'he0,8'he0,8'h61,8'h61,8'hc7,8'hc7,8'hff,8'h00,8'h00,8'h61,8'h00,8'h00,8'h20,8'hc7,8'hc6,8'h61,8'h61,8'h61,8'h21,8'h21,8'h21,8'h21,8'h00,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0},
	{8'he0,8'he0,8'he0,8'he0,8'he0,8'h61,8'h20,8'h00,8'h00,8'h24,8'h24,8'h00,8'hff,8'hff,8'hff,8'hc7,8'hc7,8'hc7,8'h61,8'h61,8'h61,8'h21,8'h21,8'h21,8'h21,8'h20,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0},
	{8'he0,8'he0,8'h00,8'hff,8'hfb,8'hf7,8'hf7,8'hf7,8'hf7,8'hf7,8'hf7,8'hf7,8'h6d,8'hff,8'h25,8'h00,8'hc7,8'hc7,8'h61,8'h61,8'h61,8'h21,8'h21,8'h21,8'h21,8'h21,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0},
	{8'he0,8'he0,8'hff,8'hf7,8'hf7,8'hf7,8'hf7,8'hf7,8'hf7,8'h00,8'hff,8'hff,8'hff,8'hfb,8'hfb,8'h00,8'hc7,8'hc7,8'ha2,8'h61,8'h21,8'h21,8'h21,8'h21,8'h20,8'h20,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0},
	{8'he0,8'he0,8'hff,8'hf7,8'hf7,8'hf7,8'h00,8'hc6,8'h00,8'hf3,8'hf3,8'hf3,8'hf3,8'hf3,8'h00,8'hc7,8'hc7,8'hc7,8'h61,8'h61,8'h21,8'h21,8'h21,8'h21,8'h21,8'h20,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0},
	{8'he0,8'he0,8'he0,8'hf7,8'hf7,8'ha0,8'he0,8'hce,8'hc7,8'hc7,8'h85,8'hf3,8'hd3,8'ha6,8'hc7,8'hc7,8'hc6,8'h61,8'h61,8'h61,8'h21,8'h21,8'h21,8'h00,8'h00,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0},
	{8'he0,8'he0,8'he0,8'hff,8'hf7,8'hfb,8'h20,8'h61,8'h61,8'hc7,8'hc7,8'hc7,8'hc7,8'hc7,8'hc7,8'hc7,8'h61,8'h61,8'h61,8'h20,8'h00,8'h21,8'h21,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0},
	{8'he0,8'he0,8'he0,8'he0,8'he0,8'h00,8'he0,8'he0,8'h61,8'h61,8'hc6,8'h61,8'hc7,8'hc7,8'hc7,8'h61,8'h61,8'h61,8'h21,8'h20,8'h20,8'h21,8'he0,8'he0,8'he0,8'he0,8'h00,8'he0,8'he0,8'he0,8'he0,8'he0},
	{8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'h81,8'h20,8'h61,8'ha2,8'h61,8'h61,8'h61,8'h61,8'h21,8'hd6,8'h20,8'h80,8'he0,8'he0,8'h00,8'h00,8'he0,8'hc0,8'h00,8'he0,8'he0,8'he0},
	{8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'h61,8'h24,8'h61,8'h00,8'hff,8'h61,8'h21,8'hd7,8'hd6,8'h00,8'h00,8'h00,8'h00,8'he0,8'h00,8'h00,8'he0,8'he0,8'he0,8'he0,8'he0},
	{8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'hff,8'hff,8'hff,8'hff,8'h6d,8'hfb,8'hd6,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0},
	{8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'hb6,8'hd6,8'hd6,8'hd6,8'h24,8'he0,8'he0,8'h00,8'h00,8'h20,8'he0,8'h60,8'h00,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0},
	{8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'h80,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'h00,8'h00,8'hc0,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0},
	{8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0},
	{8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0},
	{8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0},
	{8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0}};

 
 
//////////--------------------------------------------------------------------------------------------------------------= 
//hit bit map has one bit per edge:  hit_colors[3:0] =   {Left, Top, Right, Bottom}	 
//there is one bit per edge, in the corner two bits are set  
 logic [0:3] [0:3] [3:0] hit_colors = 
		   {16'hC446,     
			16'h8C62,    
			16'h8932, 
			16'h9113}; 
 // pipeline (ff) to get the pixel color from the array 	 
//////////--------------------------------------------------------------------------------------------------------------= 
always_ff@(posedge clk or negedge resetN) 
begin 
	if(!resetN) begin 
		RGBout <=	8'h00; 
		HitEdgeCode <= 4'h0; 
	end 
	else begin 
		RGBout <= TRANSPARENT_ENCODING ; // default  
		HitEdgeCode <= 4'h0; 
		
//		if(birdCollision == 1'b1) begin
//			RGBout <= TRANSPARENT_ENCODING;
//		end
 
		if (InsideRectangle == 1'b1 ) 
		begin // inside an external bracket  
			HitEdgeCode <= hit_colors[offsetY >> 3][offsetX >> 3]; // get hitting edge from the colors table
			if(left == 1'b0)
				RGBout <= object_colors[offsetY][offsetX];
			else
				RGBout <= object_colors[offsetY][32 - offsetX - 1];
		end  	 
		 
	end 
end 
 
//////////--------------------------------------------------------------------------------------------------------------= 
// decide if to draw the pixel or not 
assign drawingRequest = (RGBout != TRANSPARENT_ENCODING ) ? 1'b1 : 1'b0 ; // get optional transparent command from the bitmpap   
 
endmodule 

