// bitmap file 
// (c) Technion IIT, Department of Electrical and Computer Engineering 2023 
// generated by the automatic Python tool 
 
 
 module objectsBitMap (

					input	logic	clk, 
					input	logic	resetN, 
					input logic	[10:0] offsetX,// offset from top left  position 
					input logic	[10:0] offsetY, 
					input	logic	InsideRectangle, //input that the pixel is within a bracket 
					input logic balloonCollision,
					input logic coinCollision,
					input logic bulletCollision,
					input logic unsigned [2:0] randSelect,
					input logic outOfScreenFlag,
					
 
					output logic balloondrawingRequest, //output that the pixel should be dispalyed 
					output logic coindrawingRequest,
					output logic [7:0] RGBout,  //rgb value from the bitmap 
					output logic [3:0] HitEdgeCode //one bit per edge 
 ) ; 
 
localparam  int OBJECT_NUMBER_OF_Y_BITS = 5;  // 2^5 = 32 
localparam  int OBJECT_NUMBER_OF_X_BITS = 5;  // 2^5 = 32 

localparam  int OBJECT_HEIGHT_Y_DIVIDER = OBJECT_NUMBER_OF_Y_BITS -2; //how many pixel bits are in every collision pixel
localparam  int OBJECT_WIDTH_X_DIVIDER =  OBJECT_NUMBER_OF_X_BITS -2;

logic [0:15] [0:15] [0:3]  MazeBitMapMask ;  

logic [0:6] [0:15] [0:15] [0:3]  MazeDefaultBitMapMask= { // defult table to load on reset 
{{64'h0000000000000000},
 {64'h0000000000000000},
 {64'h0000000002222000},
 {64'h0002200001111000},
 {64'h0000000001111000},
 {64'h0000000000000000},
 {64'h0000020000000000},
 {64'h0000000000002000},
 {64'h0000000001120000},
 {64'h0000000002220000},
 {64'h0000000000000000},
 {64'h0110000000000000},
 {64'h2200000000000001},
 {64'h0000000000000000},
 {64'h0000000000000000},
 {64'h0000000000000000}
},
{{64'h0000000000000000},
 {64'h0000000000000000},
 {64'h0021120000000001},
 {64'h0000000000000000},
 {64'h0000000002222000},
 {64'h0000000020100120},
 {64'h2000002200000020},
 {64'h0000001100000000},
 {64'h0000000000000000},
 {64'h1000000000000000},
 {64'h0000000000000221},
 {64'h0000000000000000},
 {64'h1200000000000000},
 {64'h0000000000000000},
 {64'h0000000000000000},
 {64'h0000000000000000}
},
{{64'h0000000000000000},
 {64'h1100000000000011},
 {64'h0000002000000000},
 {64'h0022222200100200},
 {64'h0010010000000000},
 {64'h0000000000000000},
 {64'h0000000200000000},
 {64'h0000020000000000},
 {64'h0000000000000000},
 {64'h1100000000000001},
 {64'h0000000000002000},
 {64'h1000000000222000},
 {64'h0000000000000000},
 {64'h0000000000000000},
 {64'h0000000000000000},
 {64'h0000000000000000}
},
{{64'h0000000000000000},
 {64'h0000000010000022},
 {64'h0000000000000000},
 {64'h0000010000000100},
 {64'h0000000000000000},
 {64'h0000000000010000},
 {64'h2202000000000000},
 {64'h1102000000200000},
 {64'h2202001000000000},
 {64'h0000000000002000},
 {64'h0002200000000000},
 {64'h0002200000000000},
 {64'h0022000011002201},
 {64'h0000000000000000},
 {64'h0000000000000000},
 {64'h0000000000000000}
}, 
{{64'h0000000000000000},
 {64'h0000000000000000},
 {64'h0000000001001000},
 {64'h0010000011100000},
 {64'h0000000000000000},
 {64'h0000022000000000},
 {64'h0000000000000002},
 {64'h0000000000000002},
 {64'h0000000000000002},
 {64'h0000000222200002},
 {64'h0000000000000001},
 {64'h0000000000000001},
 {64'h0111000000000001},
 {64'h0000000000000000},
 {64'h0000000000000000},
 {64'h0000000000000000}}
 ,
 
{{64'h0000000000000000},
 {64'h0000000000000000},
 {64'h0000022220000000},
 {64'h0000011110000000},
 {64'h0000022220000000},
 {64'h0000000000000112},
 {64'h0000000000000000},
 {64'h0000000000000001},
 {64'h0000000000000001},
 {64'h0000000000000002},
 {64'h0000120000000001},
 {64'h0000112020000002},
 {64'h0000222101000002},
 {64'h0000000000000000},
 {64'h0000000000000000},
 {64'h0000000000000000}}
 ,
 
{{64'h0000000000000000},
 {64'h1000000000000000},
 {64'h0000010000000000},
 {64'h2221000000010000},
 {64'h2221000000001100},
 {64'h2221000000002100},
 {64'h1111000000002100},
 {64'h0000000000002000},
 {64'h0000000011100000},
 {64'h0000000011000001},
 {64'h0000000010000001},
 {64'h0001111120000000},
 {64'h1000000220000001},
 {64'h0000000000000000},
 {64'h0000000000000000},
 {64'h0000000000000000}}};
  
// generating the bitmap 
 

localparam logic [7:0] TRANSPARENT_ENCODING = 8'he0 ;// RGB value in the bitmap representing a transparent pixel  
logic[0:1][0:31][0:31][7:0] object_colors = { 
	{//coin bitmap
	{8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0},
	{8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0},
	{8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'h64,8'h64,8'h64,8'h64,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0},
	{8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'h64,8'h8c,8'hfc,8'hff,8'hfa,8'h64,8'h84,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0},
	{8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'h64,8'h84,8'h64,8'h64,8'hf4,8'hfd,8'hfc,8'hfc,8'hfe,8'h20,8'h64,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0},
	{8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'h64,8'h60,8'hfc,8'hfc,8'hfd,8'hf4,8'hf4,8'hfc,8'hfc,8'hfc,8'hfc,8'hd5,8'h84,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0},
	{8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'h64,8'hfc,8'hfe,8'hfc,8'hfc,8'hfc,8'hfc,8'hfe,8'hfc,8'hfc,8'hfc,8'hfc,8'h64,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0},
	{8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'h8d,8'hf4,8'hf4,8'hfc,8'hfc,8'hfc,8'hfc,8'hfd,8'hfd,8'hfd,8'hfc,8'hfc,8'hfe,8'h64,8'h76,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0},
	{8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'h6d,8'h64,8'hfd,8'hfc,8'hfe,8'hff,8'hfc,8'hfc,8'hfc,8'hfc,8'hfc,8'hfc,8'hfc,8'hff,8'h64,8'h64,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0},
	{8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'h91,8'h60,8'hfc,8'hfd,8'hfe,8'hfc,8'hfc,8'hf8,8'hcc,8'h84,8'h84,8'h80,8'hf8,8'hfc,8'hfc,8'hfd,8'h64,8'h64,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0},
	{8'he0,8'he0,8'he0,8'he0,8'he0,8'h76,8'h64,8'hfc,8'hfe,8'hfc,8'hfc,8'hfc,8'hd0,8'hfc,8'hfc,8'hfc,8'hfc,8'hfc,8'hfc,8'hcc,8'h84,8'hf8,8'hfc,8'hff,8'h64,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0},
	{8'he0,8'he0,8'he0,8'he0,8'he0,8'h84,8'hfc,8'hfe,8'hfc,8'hfc,8'h84,8'hfc,8'hfe,8'hfe,8'hfe,8'hfe,8'hfc,8'hfc,8'hfc,8'hfc,8'hfc,8'hcc,8'hf8,8'hfc,8'h60,8'h84,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0},
	{8'he0,8'he0,8'he0,8'he0,8'h64,8'hd9,8'hfc,8'hfe,8'hfc,8'ha4,8'hfc,8'hfc,8'hfe,8'hfe,8'hfe,8'hfe,8'hfc,8'hfc,8'hfc,8'hfc,8'hfc,8'hfc,8'hac,8'hf8,8'hfe,8'h64,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0},
	{8'he0,8'he0,8'he0,8'he0,8'h64,8'hfd,8'hfe,8'hfc,8'hf8,8'hfc,8'ha4,8'h80,8'hf9,8'hfe,8'hfe,8'hfc,8'hfc,8'hfc,8'hfc,8'hfc,8'hf5,8'h80,8'ha4,8'hf0,8'hfc,8'hd6,8'h64,8'he0,8'he0,8'he0,8'he0,8'he0},
	{8'he0,8'he0,8'he0,8'h64,8'h60,8'hfe,8'hfe,8'hfc,8'hf4,8'hd5,8'ha4,8'ha4,8'ha4,8'h80,8'h80,8'hfc,8'hfc,8'hfc,8'h80,8'ha4,8'ha4,8'ha4,8'ha4,8'hfd,8'hf8,8'hfd,8'h64,8'he0,8'he0,8'he0,8'he0,8'he0},
	{8'he0,8'he0,8'he0,8'h64,8'hfe,8'hfe,8'hfc,8'hf8,8'hfc,8'hfc,8'hfc,8'hac,8'h84,8'ha4,8'ha4,8'ha4,8'h80,8'ha4,8'ha4,8'ha4,8'h84,8'ha4,8'hfc,8'hfc,8'h84,8'hfc,8'h64,8'he0,8'he0,8'he0,8'he0,8'he0},
	{8'he0,8'he0,8'he0,8'h64,8'hff,8'hff,8'hfc,8'hf4,8'hfc,8'hfc,8'hfc,8'hfe,8'hff,8'hff,8'h80,8'hfd,8'ha4,8'ha4,8'h80,8'hfe,8'hff,8'hfd,8'hfc,8'hfc,8'hf4,8'hfc,8'h60,8'he0,8'he0,8'he0,8'he0,8'he0},
	{8'he0,8'he0,8'he0,8'h64,8'hff,8'hff,8'hfc,8'hac,8'hf8,8'hfc,8'hf4,8'hff,8'hff,8'hff,8'ha4,8'hff,8'h84,8'hfa,8'ha4,8'hff,8'hff,8'hfe,8'hfc,8'hfc,8'hf8,8'hfc,8'h60,8'he0,8'he0,8'he0,8'he0,8'he0},
	{8'he0,8'he0,8'he0,8'h64,8'hf4,8'hfe,8'hfc,8'hcc,8'hf4,8'hfc,8'hf4,8'h84,8'hff,8'hff,8'h8c,8'hfe,8'hff,8'hfe,8'hfa,8'hff,8'hff,8'hf8,8'hfc,8'hf8,8'hf8,8'hfc,8'h60,8'he0,8'he0,8'he0,8'he0,8'he0},
	{8'he0,8'he0,8'he0,8'h64,8'hf4,8'hf8,8'hfc,8'hfc,8'hf4,8'hfc,8'hfc,8'hf4,8'hf4,8'h80,8'hfc,8'hfc,8'hfe,8'hfc,8'hfc,8'hac,8'hf8,8'hf4,8'hfc,8'hf4,8'ha4,8'hfc,8'h64,8'he0,8'he0,8'he0,8'he0,8'he0},
	{8'he0,8'he0,8'he0,8'h84,8'hac,8'hf4,8'hfc,8'hfc,8'hf8,8'hfc,8'hfc,8'hf8,8'hff,8'hfc,8'hfc,8'hfc,8'hfc,8'hfc,8'hfc,8'hfc,8'hf9,8'hfc,8'hfc,8'hfc,8'hac,8'hfc,8'h64,8'he0,8'he0,8'he0,8'he0,8'he0},
	{8'he0,8'he0,8'he0,8'he0,8'h64,8'hf4,8'hfe,8'hfc,8'h84,8'hfc,8'hfc,8'hfc,8'h84,8'hfe,8'hfc,8'hfc,8'hfc,8'hfc,8'hfc,8'hfc,8'h80,8'hfc,8'hfc,8'hf8,8'hfd,8'hfc,8'h64,8'he0,8'he0,8'he0,8'he0,8'he0},
	{8'he0,8'he0,8'he0,8'he0,8'h64,8'hf4,8'hf0,8'hfc,8'hfe,8'hfc,8'hfc,8'hfc,8'hfc,8'h60,8'hfc,8'hf4,8'h84,8'ha4,8'hfc,8'h80,8'hfc,8'hfc,8'hfc,8'h64,8'hfc,8'h84,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0},
	{8'he0,8'he0,8'he0,8'he0,8'he0,8'h64,8'hf4,8'hfe,8'hfc,8'hff,8'hfc,8'hfc,8'hfc,8'hfd,8'hf9,8'hfc,8'hfc,8'hfc,8'ha4,8'hf8,8'hfc,8'hfc,8'h84,8'hfc,8'hfc,8'h64,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0},
	{8'he0,8'he0,8'he0,8'he0,8'he0,8'h84,8'hf9,8'hf4,8'hfd,8'hfc,8'hff,8'hfd,8'hfc,8'hfc,8'hfc,8'h64,8'hfc,8'ha4,8'hfc,8'hfc,8'hfc,8'h84,8'hfc,8'hfc,8'h84,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0},
	{8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'h64,8'hf4,8'hf4,8'hfe,8'hfc,8'hfd,8'ha4,8'hfc,8'hfc,8'hfc,8'hfe,8'hfc,8'hfc,8'h60,8'hff,8'hfc,8'hfc,8'h64,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0},
	{8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'h64,8'hf4,8'hf4,8'hfc,8'hfc,8'hfc,8'hfc,8'hfe,8'hfe,8'hfe,8'hff,8'hfe,8'hfc,8'hfc,8'hfd,8'h84,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0},
	{8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'h6c,8'h64,8'hf4,8'hf4,8'hf0,8'hfc,8'hfc,8'hfc,8'hfc,8'hfc,8'hfc,8'hf4,8'h64,8'h64,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0},
	{8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'h84,8'h64,8'h60,8'hcc,8'hf4,8'hf4,8'hcc,8'h60,8'h64,8'h64,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0},
	{8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'h84,8'h84,8'h76,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0},
	{8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0},
	{8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0}
	},
	{//balloon bitmap
	{8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0},
	{8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0},
	{8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'h20,8'h00,8'h00,8'h91,8'h91,8'h6d,8'h00,8'h00,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0},
	{8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'h00,8'h91,8'h91,8'h91,8'h91,8'h91,8'hda,8'hda,8'hda,8'hb6,8'h91,8'h91,8'h00,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0},
	{8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'h00,8'h91,8'h91,8'h91,8'h91,8'h91,8'h91,8'h91,8'h91,8'h91,8'h91,8'h91,8'hda,8'hda,8'hda,8'h91,8'h00,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0},
	{8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'h00,8'h91,8'h91,8'h91,8'h91,8'h91,8'h91,8'h91,8'h91,8'h91,8'h91,8'h91,8'h91,8'h91,8'h91,8'h91,8'hb6,8'hda,8'hda,8'h24,8'he0,8'he0,8'he0,8'he0,8'he0},
	{8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'h00,8'h91,8'h91,8'h91,8'h91,8'h91,8'h91,8'h91,8'h91,8'h91,8'h91,8'h91,8'h91,8'h91,8'h91,8'h91,8'h91,8'h91,8'h91,8'hda,8'hda,8'h91,8'he0,8'he0,8'he0,8'he0},
	{8'he0,8'he0,8'he0,8'he0,8'he0,8'h00,8'h91,8'h91,8'h91,8'h91,8'h91,8'h91,8'h91,8'h91,8'h91,8'h91,8'h91,8'h91,8'h91,8'h91,8'h91,8'h91,8'h91,8'h91,8'h91,8'h91,8'h91,8'hda,8'h91,8'he0,8'he0,8'he0},
	{8'he0,8'he0,8'he0,8'he0,8'h00,8'hda,8'h91,8'h91,8'h91,8'h91,8'h91,8'h91,8'h91,8'h91,8'h91,8'h91,8'h91,8'h91,8'h91,8'h91,8'h91,8'h91,8'h91,8'h91,8'h91,8'h91,8'h91,8'h91,8'h91,8'h00,8'he0,8'he0},
	{8'he0,8'he0,8'he0,8'he0,8'hda,8'h91,8'h91,8'h91,8'h91,8'h91,8'h91,8'h91,8'h91,8'h91,8'h91,8'h91,8'h91,8'h91,8'h91,8'h91,8'h91,8'h91,8'h91,8'h91,8'h91,8'h91,8'h91,8'h91,8'h91,8'h91,8'he0,8'he0},
	{8'he0,8'he0,8'he0,8'h00,8'hda,8'h91,8'h91,8'h91,8'h91,8'h91,8'h91,8'h91,8'h91,8'h91,8'h91,8'h91,8'h91,8'h91,8'h91,8'h91,8'h91,8'h91,8'h91,8'h91,8'h91,8'h91,8'h91,8'h91,8'h91,8'h91,8'h80,8'he0},
	{8'he0,8'he0,8'he0,8'hda,8'hb6,8'h91,8'h91,8'h91,8'h91,8'h91,8'h91,8'h91,8'h91,8'h91,8'h91,8'h91,8'h91,8'h91,8'h91,8'h91,8'h91,8'h91,8'h91,8'h91,8'h91,8'h91,8'h91,8'h91,8'h91,8'h91,8'h00,8'he0},
	{8'he0,8'he0,8'he0,8'hda,8'h91,8'h91,8'h91,8'h91,8'h91,8'h91,8'h91,8'h91,8'h91,8'h91,8'h91,8'h91,8'h91,8'h91,8'h91,8'h91,8'h91,8'h91,8'h91,8'h91,8'h91,8'h91,8'h91,8'h91,8'h91,8'h91,8'h00,8'he0},
	{8'he0,8'he0,8'h00,8'hda,8'h91,8'h91,8'h91,8'h91,8'h91,8'h91,8'h91,8'h91,8'h91,8'h91,8'h91,8'h91,8'h91,8'h91,8'h91,8'h91,8'h91,8'h91,8'h91,8'h91,8'h91,8'h91,8'h91,8'h91,8'h91,8'h91,8'h00,8'he0},
	{8'he0,8'he0,8'h00,8'hda,8'h91,8'h91,8'h91,8'h91,8'h91,8'h91,8'h91,8'h91,8'h91,8'h91,8'h91,8'h91,8'h91,8'h91,8'h91,8'h91,8'h91,8'h91,8'h91,8'h91,8'h91,8'h91,8'h91,8'h91,8'h91,8'h91,8'h00,8'he0},
	{8'he0,8'he0,8'h00,8'hda,8'h91,8'h91,8'h91,8'h91,8'h91,8'h91,8'h91,8'h91,8'h91,8'h91,8'h91,8'h91,8'h91,8'h91,8'h91,8'h91,8'h91,8'h91,8'h91,8'h91,8'h91,8'h91,8'h91,8'h91,8'h91,8'h91,8'h00,8'he0},
	{8'he0,8'he0,8'h00,8'hda,8'h91,8'h91,8'h91,8'h91,8'h91,8'h91,8'h91,8'h91,8'h6d,8'h6d,8'h6d,8'h71,8'h74,8'h74,8'h71,8'h6d,8'h6d,8'h6d,8'h6d,8'h91,8'h91,8'h91,8'h91,8'h91,8'h91,8'h91,8'h00,8'he0},
	{8'he0,8'he0,8'h00,8'hda,8'h91,8'h91,8'h91,8'h91,8'h91,8'h6d,8'h6d,8'h00,8'h00,8'h74,8'hdc,8'hdc,8'hdc,8'hdc,8'hfc,8'hdc,8'h74,8'h00,8'h00,8'h00,8'h24,8'h6d,8'h6d,8'h91,8'h91,8'h91,8'h00,8'he0},
	{8'he0,8'he0,8'h00,8'hda,8'h91,8'h91,8'h6d,8'h24,8'h00,8'h78,8'h9d,8'h9d,8'h74,8'hdc,8'hdc,8'hdc,8'hdc,8'hdc,8'hdc,8'hdc,8'hfc,8'h74,8'h9d,8'h9d,8'h9d,8'h9d,8'h30,8'h00,8'h00,8'h00,8'h80,8'he0},
	{8'he0,8'he0,8'h00,8'hda,8'hb6,8'h00,8'h30,8'h95,8'hff,8'h95,8'h9d,8'h9d,8'hdc,8'hdc,8'hdc,8'hdc,8'hdc,8'hdc,8'hdc,8'hdc,8'hdc,8'hdc,8'h9d,8'h9d,8'hda,8'hff,8'h70,8'h9d,8'h8c,8'he0,8'he0,8'he0},
	{8'he0,8'he0,8'he0,8'h00,8'h8c,8'h20,8'hff,8'hff,8'hff,8'hff,8'hba,8'h74,8'hdc,8'hdc,8'hdc,8'h04,8'hdc,8'hdc,8'h04,8'hdc,8'hdc,8'hfc,8'h9c,8'hff,8'hff,8'hff,8'hff,8'h70,8'h8c,8'he0,8'he0,8'he0},
	{8'he0,8'he0,8'he0,8'hc0,8'h8c,8'h70,8'hff,8'h00,8'hff,8'hff,8'hff,8'h74,8'hdc,8'hdc,8'h04,8'h04,8'h30,8'h04,8'h04,8'hdc,8'hdc,8'hdc,8'h78,8'hff,8'hff,8'hff,8'h00,8'hff,8'h8c,8'h80,8'he0,8'he0},
	{8'he0,8'he0,8'he0,8'h20,8'h8c,8'h9d,8'hff,8'hff,8'hff,8'hff,8'hff,8'h9d,8'hdc,8'hdc,8'hdc,8'h04,8'hdc,8'h70,8'h04,8'hdc,8'hdc,8'hdc,8'h78,8'hff,8'hff,8'hff,8'hff,8'hda,8'h8c,8'h60,8'he0,8'he0},
	{8'he0,8'he0,8'he0,8'h84,8'h8c,8'h38,8'h70,8'hff,8'hff,8'hff,8'h78,8'h9d,8'h74,8'hdc,8'hdc,8'hdc,8'hdc,8'hdc,8'hdc,8'hdc,8'hdc,8'h74,8'h78,8'h74,8'hff,8'hff,8'hff,8'h9d,8'h8c,8'h20,8'he0,8'he0},
	{8'he0,8'he0,8'he0,8'h8c,8'h8c,8'h00,8'h7c,8'h78,8'h70,8'h78,8'h78,8'h9d,8'h9d,8'h74,8'hbc,8'hdc,8'hdc,8'hdc,8'hdc,8'hdc,8'h74,8'h9d,8'h9d,8'h78,8'h74,8'h70,8'h78,8'h00,8'h8c,8'h64,8'he0,8'he0},
	{8'he0,8'he0,8'he0,8'h20,8'h60,8'he0,8'h00,8'h9d,8'h9d,8'h9d,8'h9d,8'h9d,8'h9d,8'h74,8'h98,8'h94,8'h74,8'h74,8'h74,8'h9d,8'h9d,8'h9d,8'h9d,8'h9d,8'h9d,8'h9d,8'h9d,8'hc0,8'h8c,8'h8c,8'he0,8'he0},
	{8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'h00,8'h9d,8'h9d,8'h9d,8'h9d,8'h9d,8'h9d,8'h74,8'h94,8'h74,8'h9d,8'h9d,8'h9d,8'h9d,8'h9d,8'h9d,8'h9d,8'h9d,8'h9d,8'h00,8'he0,8'he0,8'he0,8'he0,8'he0},
	{8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'h00,8'h38,8'h9d,8'h9d,8'h9d,8'h9d,8'h9d,8'h9d,8'h9d,8'h9d,8'h9d,8'h9d,8'h9d,8'h9d,8'h9d,8'h9d,8'h0c,8'h00,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0},
	{8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'h00,8'h00,8'h38,8'h38,8'h9d,8'h9d,8'h9d,8'h9d,8'h9d,8'h9d,8'h9d,8'h9d,8'h78,8'h38,8'h00,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0},
	{8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'h00,8'h00,8'h00,8'h38,8'h38,8'h38,8'h38,8'h38,8'h04,8'h00,8'h00,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0},
	{8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0},
	{8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0}}};


//////////--------------------------------------------------------------------------------------------------------------= 
//hit bit map has one bit per edge:  hit_colors[3:0] =   {Left, Top, Right, Bottom}	 
//there is one bit per edge, in the corner two bits are set  
 logic [0:3] [0:3] [3:0] hit_colors = 
		   {16'hC446,     
			16'h8C62,    
			16'h8932, 
			16'h9113}; 
 // pipeline (ff) to get the pixel color from the array 	 
//////////--------------------------------------------------------------------------------------------------------------= 
always_ff@(posedge clk or negedge resetN) 
begin 
	if(!resetN) begin 
		RGBout <=	8'he0; 
		HitEdgeCode <= 4'h0;
		MazeBitMapMask  <=  MazeDefaultBitMapMask[randSelect];	
	end 
	else begin 
		RGBout <= TRANSPARENT_ENCODING ; // default  
		HitEdgeCode <= 4'h0; 
		
		if(outOfScreenFlag == 1'b1) begin
			MazeBitMapMask  <=  MazeDefaultBitMapMask[randSelect];
		end
		
		if(bulletCollision == 1'b1) begin
			MazeBitMapMask[offsetY[8:5]][offsetX[8:5]] <= 4'h0;
		end
		
		if(balloonCollision == 1'b1) begin
			HitEdgeCode <= hit_colors[offsetY >> OBJECT_HEIGHT_Y_DIVIDER][offsetX >> OBJECT_WIDTH_X_DIVIDER]; // get hitting edge from the colors table
		end
			
		if(coinCollision == 1'b1) begin
			MazeBitMapMask[offsetY[8:5]][offsetX[8:5]] <= 4'h0;
		end

		if (InsideRectangle == 1'b1 )  	 
		begin // inside an external bracket  
			case (MazeBitMapMask[offsetY[8:5]][offsetX[8:5]])
				 4'h0 : RGBout <= TRANSPARENT_ENCODING;
				 4'h1 : RGBout <= object_colors[0][offsetY[4:0]][offsetX[4:0]]; 
				 4'h2 : RGBout <= object_colors[1][offsetY[4:0]][offsetX[4:0]];
				 default:  RGBout <= TRANSPARENT_ENCODING ; 
			endcase 
		end 
		
	end 
end 
 
//////////--------------------------------------------------------------------------------------------------------------= 
// decide if to draw the pixel or not 
assign coindrawingRequest = (RGBout != TRANSPARENT_ENCODING ) && (MazeBitMapMask[offsetY[8:5]][offsetX[8:5]] == 1) ? 1'b1 : 1'b0 ;
assign balloondrawingRequest = (RGBout != TRANSPARENT_ENCODING ) && (MazeBitMapMask[offsetY[8:5]][offsetX[8:5]] == 2) ? 1'b1 : 1'b0 ; // get optional transparent command from the bitmpap   
 
endmodule 
