// bitmap file 
// (c) Technion IIT, Department of Electrical and Computer Engineering 2023 
// generated by the automatic Python tool 
 
 
 module heartBitMap (

					input	logic	clk, 
					input	logic	resetN, 
					input logic	[10:0] offsetX,// offset from top left  position 
					input logic	[10:0] offsetY, 
					input	logic	InsideRectangle, //input that the pixel is within a bracket 
					input logic birdCollisionL,
					input logic birdCollisionR,
					input logic stopGame,
					
					output	logic	heartDrawingRequest, //output that the pixel should be dispalyed 
					output	logic	[7:0] RGBout, //rgb value from the bitmap  
					output 	logic gameLost
 ) ; 
 
 
logic [0:3] MazeBitMapMask ;  

logic [0:3] MazeDefaultBitMapMask4= {4'b1111};
logic [0:3] MazeDefaultBitMapMask3= {4'b1110};
logic [0:3] MazeDefaultBitMapMask2= {4'b1100};
logic [0:3] MazeDefaultBitMapMask1= {4'b1000};
logic [0:3] MazeDefaultBitMapMask0= {4'b0000};
 
// generating the bitmap 
 

localparam logic [7:0] TRANSPARENT_ENCODING = 8'hfc ;// RGB value in the bitmap representing a transparent pixel  
logic[0:1][0:15][0:15][7:0] object_colors = {
	{{8'hfc,8'hfc,8'hfc,8'h00,8'h00,8'h00,8'hfc,8'hfc,8'hfc,8'hfc,8'h00,8'h00,8'h00,8'h00,8'hfc,8'hfc},
	{8'hfc,8'hfc,8'h00,8'he0,8'he0,8'he0,8'h00,8'hfc,8'hfc,8'h00,8'he0,8'he0,8'he0,8'he0,8'hfc,8'hfc},
	{8'hfc,8'h00,8'he0,8'hff,8'hff,8'hff,8'he0,8'h00,8'h24,8'he0,8'he0,8'he0,8'he0,8'he0,8'h00,8'hfc},
	{8'hfc,8'h00,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'hc0,8'he0,8'he0,8'he0,8'he0,8'he0,8'h00,8'hfc},
	{8'h00,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'h00},
	{8'h00,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'h00},
	{8'h00,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'h00},
	{8'hfc,8'h00,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'h00,8'hfc},
	{8'hfc,8'hfc,8'h00,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'hc0,8'hfc,8'hfc},
	{8'hfc,8'hfc,8'hfc,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'h00,8'hfc,8'hfc},
	{8'hfc,8'hfc,8'hfc,8'h00,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'h00,8'hfc,8'hfc,8'hfc},
	{8'hfc,8'hfc,8'hfc,8'hfc,8'h00,8'he0,8'he0,8'he0,8'he0,8'he0,8'he0,8'h00,8'hfc,8'hfc,8'hfc,8'hfc},
	{8'hfc,8'hfc,8'hfc,8'hfc,8'hfc,8'hfc,8'he0,8'he0,8'he0,8'he0,8'h00,8'hfc,8'hfc,8'hfc,8'hfc,8'hfc},
	{8'hfc,8'hfc,8'hfc,8'hfc,8'hfc,8'hfc,8'h00,8'he0,8'he0,8'h00,8'hfc,8'hfc,8'hfc,8'hfc,8'hfc,8'hfc},
	{8'hfc,8'hfc,8'hfc,8'hfc,8'hfc,8'hfc,8'hfc,8'h00,8'h60,8'hfc,8'hfc,8'hfc,8'hfc,8'hfc,8'hfc,8'hfc},
	{8'hfc,8'hfc,8'hfc,8'hfc,8'hfc,8'hfc,8'hfc,8'hfc,8'hfc,8'hfc,8'hfc,8'hfc,8'hfc,8'hfc,8'hfc,8'hfc}
	},
	{{8'hfc,8'hfc,8'hfc,8'h00,8'h00,8'h00,8'hfc,8'hfc,8'hfc,8'hfc,8'h00,8'h00,8'h00,8'h00,8'hfc,8'hfc},
	{8'hfc,8'hfc,8'h00,8'hfc,8'hfc,8'hfc,8'h00,8'hfc,8'hfc,8'h00,8'hfc,8'hfc,8'hfc,8'hfc,8'hfc,8'hfc},
	{8'hfc,8'h00,8'hfc,8'hff,8'hff,8'hff,8'hfc,8'h00,8'h24,8'hfc,8'hfc,8'hfc,8'hfc,8'hfc,8'h00,8'hfc},
	{8'hfc,8'h00,8'hfc,8'hfc,8'hfc,8'hfc,8'hfc,8'hfc,8'hc0,8'hfc,8'hfc,8'hfc,8'hfc,8'hfc,8'h00,8'hfc},
	{8'hd8,8'hfc,8'hfc,8'hfc,8'hfc,8'hfc,8'hfc,8'hfc,8'hfc,8'hfc,8'hfc,8'hfc,8'hfc,8'hfc,8'hfc,8'h00},
	{8'hd8,8'hfc,8'hfc,8'hfc,8'hfc,8'hfc,8'hfc,8'hfc,8'hfc,8'hfc,8'hfc,8'hfc,8'hfc,8'hfc,8'hfc,8'h00},
	{8'hd8,8'hfc,8'hfc,8'hfc,8'hfc,8'hfc,8'hfc,8'hfc,8'hfc,8'hfc,8'hfc,8'hfc,8'hfc,8'hfc,8'hfc,8'h00},
	{8'hfc,8'h00,8'hfc,8'hfc,8'hfc,8'hfc,8'hfc,8'hfc,8'hfc,8'hfc,8'hfc,8'hfc,8'hfc,8'hfc,8'h00,8'hfc},
	{8'hfc,8'hfc,8'h00,8'hfc,8'hfc,8'hfc,8'hfc,8'hfc,8'hfc,8'hfc,8'hfc,8'hfc,8'hfc,8'hc0,8'hfc,8'hfc},
	{8'hfc,8'hfc,8'hfc,8'hfc,8'hfc,8'hfc,8'hfc,8'hfc,8'hfc,8'hfc,8'hfc,8'hfc,8'hfc,8'h00,8'hfc,8'hfc},
	{8'hfc,8'hfc,8'hfc,8'h00,8'hfc,8'hfc,8'hfc,8'hfc,8'hfc,8'hfc,8'hfc,8'hfc,8'h00,8'hfc,8'hfc,8'hfc},
	{8'hfc,8'hfc,8'hfc,8'hfc,8'h00,8'hfc,8'hfc,8'hfc,8'hfc,8'hfc,8'hfc,8'h00,8'hfc,8'hfc,8'hfc,8'hfc},
	{8'hfc,8'hfc,8'hfc,8'hfc,8'hfc,8'hfc,8'hfc,8'hfc,8'hfc,8'hfc,8'h00,8'hfc,8'hfc,8'hfc,8'hfc,8'hfc},
	{8'hfc,8'hfc,8'hfc,8'hfc,8'hfc,8'hfc,8'h00,8'hfc,8'hfc,8'h00,8'hfc,8'hfc,8'hfc,8'hfc,8'hfc,8'hfc},
	{8'hfc,8'hfc,8'hfc,8'hfc,8'hfc,8'hfc,8'hfc,8'h00,8'h60,8'hfc,8'hfc,8'hfc,8'hfc,8'hfc,8'hfc,8'hfc},
	{8'hfc,8'hfc,8'hfc,8'hfc,8'hfc,8'hfc,8'hfc,8'hfc,8'hfc,8'hfc,8'hfc,8'hfc,8'hfc,8'hfc,8'hfc,8'hfc}}};

int collisionsNumber = 0;
int collisionL = 0;
int collisionR = 0;
int flag = 0;
 
//////////--------------------------------------------------------------------------------------------------------------= 
//hit bit map has one bit per edge:  hit_colors[3:0] =   {Left, Top, Right, Bottom}	 
//there is one bit per edge, in the corner two bits are set  
 logic [0:3] [0:3] [3:0] hit_colors = 
		   {16'hC446,     
			16'h8C62,    
			16'h8932, 
			16'h9113}; 
 // pipeline (ff) to get the pixel color from the array 	 
//////////--------------------------------------------------------------------------------------------------------------= 
always_ff@(posedge clk or negedge resetN) 
begin 
	if(!resetN) begin 
		RGBout <=	8'h00; 
		MazeBitMapMask  <=  MazeDefaultBitMapMask4;
		collisionsNumber <= 0;
		flag <= 0;
		collisionL <= 0;
		collisionR <= 0;
		gameLost <= 0;
	end 
	else begin 
		RGBout <= TRANSPARENT_ENCODING ; // default
		collisionL <= birdCollisionL;
		collisionR <= birdCollisionR;
		
		if((birdCollisionL || birdCollisionR) && flag && !stopGame) begin
			if(birdCollisionL && collisionL == 0) begin
				collisionsNumber++;
			end
			if(birdCollisionR && collisionR == 0) begin
				collisionsNumber++;
			end
				
			if(collisionsNumber == 1)
				MazeBitMapMask <= MazeDefaultBitMapMask3;
			else if(collisionsNumber == 2)
				MazeBitMapMask <= MazeDefaultBitMapMask2;
			else if(collisionsNumber == 3)
				MazeBitMapMask <= MazeDefaultBitMapMask1;
			else if(collisionsNumber == 4) begin
				MazeBitMapMask <= MazeDefaultBitMapMask0;
				gameLost <= 1;
			end
		end
		else begin
			flag <= 1'b1;
		end
 
		if (InsideRectangle == 1'b1) 
		begin // inside an external bracket  
			case (MazeBitMapMask[offsetX[5:4]])
				 1'b0 : RGBout <= object_colors[1][offsetY[3:0]][offsetX[3:0]]; 
				 1'b1 : RGBout <= object_colors[0][offsetY[3:0]][offsetX[3:0]];
				 default:  RGBout <= TRANSPARENT_ENCODING ; 
			endcase  
		end  	 	 
	end 
end 
 
//////////--------------------------------------------------------------------------------------------------------------= 
// decide if to draw the pixel or not 
assign heartDrawingRequest = (RGBout != TRANSPARENT_ENCODING ) ? 1'b1 : 1'b0 ; // get optional transparent command from the bitmpap   
 
endmodule 
